### ISSUE TITLE
Getting `Expected component to be a function`

### ISSUE THREAD

**Issue by jrschumacher** [maticzav/ink-table#5]
With a sample use of Table I get the following error.

```
/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/h.js:8
                throw new TypeError(`Expected component to be a function, but received ${typeof component}. You may have forgotten to export a component.`);
                ^

TypeError: Expected component to be a function, but received object. You may have forgotten to export a component.
    at h (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/h.js:8:9)
    at UI.render (/Users/rschumacher/Projects/test-ink/ui.js:66:12)
    at UI._render (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/component.js:54:15)
    at mount (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/diff.js:36:35)
    at diff (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/diff.js:136:3)
    at build (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/renderer.js:10:9)
    at Renderer.update (/Users/rschumacher/Projects/test-ink/node_modules/ink/lib/renderer.js:25:20)
    at exports.render (/Users/rschumacher/Projects/test-ink/node_modules/ink/index.js:59:14)
    at Object.<anonymous> (/Users/rschumacher/Projects/test-ink/cli.js:24:1)
    at Module._compile (module.js:635:30)
```

**Comment by benoitzohar** [comment]
Thanks @huaruiwu you saved my day 🍻

**Comment by maticzav** [comment]
I suppose this is not happening anymore. Feel free to reopen the issue if the problem is still relevant.
